/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulation_atm;

import DB.DbOperation;
import java.awt.Dialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudarsan
 */
public class ManageAtm extends javax.swing.JDialog {

    String address;
    String newNo = "";

    /**
     * Creates new form ManageAtm
     */
    public ManageAtm(String address, String natm) {
        this.address = address;
        initComponents();
        addresslbl.setText(address);
        availablelbl.setText(availablelbl.getText() + natm);
        this.setLocationRelativeTo(null);
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        btnAdd.setVisible(false);
        btnOk.setVisible(false);
        btnRemove.setVisible(false);
        suggestion.setVisible(false);

        DbOperation dopt = new DbOperation();
        String a = dopt.getNumberOfCustomer("A", address);
        String b = dopt.getNumberOfCustomer("B", address);

        double reqForA = Double.parseDouble(a) / 2.0;
        double reqForB = Double.parseDouble(b) / 4.0;

        double total = reqForA + reqForB;

        int itotal = (int) total;
        if (itotal == 0) {
            itotal = 1;
        }
        this.newNo += itotal;
        requiredlbl.setText(requiredlbl.getText() + itotal);

        System.out.println(itotal);
        albl.setText(albl.getText() + a);
        blbl.setText(blbl.getText() + b);

        if (itotal == Integer.parseInt(natm)) {
            btnOk.setVisible(true);
            suggestion.setText("You have accurate ATM in " + address);
        } else if (itotal > Integer.parseInt(natm)) {
            btnAdd.setVisible(true);
            suggestion.setText("You need to add " + (itotal - Integer.parseInt(natm)) + " ATM in " + address);
        } else {
            btnRemove.setVisible(true);
            suggestion.setText("You need to remove " + (Integer.parseInt(natm) - itotal) + " ATM in " + address);
        }
        suggestion.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addresslbl = new javax.swing.JLabel();
        albl = new javax.swing.JLabel();
        blbl = new javax.swing.JLabel();
        availablelbl = new javax.swing.JLabel();
        requiredlbl = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        suggestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addresslbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        addresslbl.setForeground(new java.awt.Color(153, 0, 153));
        addresslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addresslbl.setText("Address");

        albl.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        albl.setText("Number of A category customer  :::  ");

        blbl.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        blbl.setText("Number of B category customer  :::  ");

        availablelbl.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        availablelbl.setText("Total number of available ATM ::: ");

        requiredlbl.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        requiredlbl.setText("Total number of required ATM ::: ");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        suggestion.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        suggestion.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addresslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suggestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availablelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(albl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(blbl, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                .addComponent(requiredlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addresslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(availablelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requiredlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnAdd)
                            .addComponent(btnRemove)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(suggestion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DbOperation dopt = new DbOperation();
        dopt.modifyNumberOfAtm(address, newNo);
        JOptionPane.showMessageDialog(this, "Number of ATM increased to " + newNo + " in " + address);

        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DbOperation dopt = new DbOperation();
        dopt.modifyNumberOfAtm(address, newNo);
        JOptionPane.showMessageDialog(this, "Number of ATM decreased to " + newNo + " in " + address);

        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel albl;
    private javax.swing.JLabel availablelbl;
    private javax.swing.JLabel blbl;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel requiredlbl;
    private javax.swing.JLabel suggestion;
    // End of variables declaration//GEN-END:variables
}
