/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulation_atm;

import DB.DbOperation;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sudarsan
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        genderGroup.add(rMale);
        genderGroup.add(rFemale);
        genderGroup.add(rOther);
        clearWarnings();
        noResultlbl.setVisible(false);
        btnDltSelectedStudent.setVisible(false);
        this.setLocationRelativeTo(null);
        dltAtmBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        firstNametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lastNametxt = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rMale = new javax.swing.JRadioButton();
        rFemale = new javax.swing.JRadioButton();
        rOther = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        fnSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnSearch = new javax.swing.JTextField();
        noResultlbl = new javax.swing.JLabel();
        btnDltSelectedStudent = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        dltAtmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseReleased(evt);
            }
        });

        jLabel10.setText("Phone Number:");

        phonetxt.setToolTipText("Home phone no.");
        phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonetxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Email:");

        jLabel5.setText("First Name:");

        firstNametxt.setToolTipText("First Name");

        jLabel6.setText("Last Name:");

        lbl.setForeground(new java.awt.Color(204, 0, 0));
        lbl.setText("Invalid Firstname!!");

        lbl1.setForeground(new java.awt.Color(204, 0, 0));
        lbl1.setText("Invalid Lastname!");

        lbl2.setForeground(new java.awt.Color(204, 0, 0));
        lbl2.setText("*Enter Gender");

        lbl3.setForeground(new java.awt.Color(204, 0, 0));
        lbl3.setText("Enter address!");

        lastNametxt.setToolTipText("Last Name");
        lastNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNametxtActionPerformed(evt);
            }
        });

        lbl4.setForeground(new java.awt.Color(204, 0, 0));
        lbl4.setText("Invalid Phone Number!!");

        jLabel7.setText("Address :");

        lbl5.setForeground(new java.awt.Color(204, 0, 0));
        lbl5.setText("Invalid Email!!");

        addresstxt.setToolTipText("Address 1");

        jLabel12.setText("Gender:");

        rMale.setText("Male");
        rMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMaleActionPerformed(evt);
            }
        });

        rFemale.setText("Female");
        rFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFemaleActionPerformed(evt);
            }
        });

        rOther.setText("Other");
        rOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rOtherActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "B" }));

        jLabel1.setText("Category:");

        lbl6.setForeground(new java.awt.Color(204, 0, 0));
        lbl6.setText("*Select category");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(167, 167, 167))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl5))
                            .addComponent(jLabel14)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rMale)
                                .addGap(18, 18, 18)
                                .addComponent(rFemale)
                                .addGap(18, 18, 18)
                                .addComponent(rOther)
                                .addGap(42, 42, 42)
                                .addComponent(lbl2))
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phonetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl6)
                                    .addComponent(lbl4)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(firstNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(282, 282, 282)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addComponent(lbl3))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl)
                    .addComponent(lastNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rMale)
                    .addComponent(rFemale)
                    .addComponent(rOther)
                    .addComponent(lbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5))
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        fnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("FirstName");

        jLabel3.setText("LastName");

        lnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnSearchKeyReleased(evt);
            }
        });

        noResultlbl.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        noResultlbl.setForeground(new java.awt.Color(255, 0, 0));
        noResultlbl.setText("No Result Found!!!!");

        btnDltSelectedStudent.setText("Delete");
        btnDltSelectedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDltSelectedStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDltSelectedStudent)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnSearch)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lnSearch)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(noResultlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noResultlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDltSelectedStudent)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("View and Manage Customer", jPanel2);

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Add ATM in new Location");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });

        dltAtmBtn.setText("Delete");
        dltAtmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltAtmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dltAtmBtn)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dltAtmBtn))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View and Manage ATM", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonetxtActionPerformed

    private void lastNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNametxtActionPerformed

    private void rMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rMaleActionPerformed

    private void rFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rFemaleActionPerformed

    private void rOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rOtherActionPerformed
    public boolean isValidEmailAddress(String email) {
        String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
        java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
        java.util.regex.Matcher m = p.matcher(email);
        return m.matches();
    }

    public boolean isNumeric(String a) {
        return a.matches("-?\\d+(\\.\\d+)?");
    }

    public boolean isAlphabet(String name) {
        return name.matches("[a-zA-Z]+");
    }

    public void clearWarnings() {
        lbl.setVisible(false);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lbl5.setVisible(false);
        lbl6.setVisible(false);

    }

    public boolean isValidInput() {
        clearWarnings();
        boolean result = true;
        if (firstNametxt.getText().isEmpty()) {
            lbl.setText("*Enter Firstname");
            lbl.setVisible(true);
            result = false;
        } else if (!isAlphabet(firstNametxt.getText())) {
            lbl.setText("Invalid Firstname!");
            lbl.setVisible(true);
            result = false;
        }
        if (lastNametxt.getText().isEmpty()) {
            lbl1.setText("*Enter Lastname");
            lbl1.setVisible(true);
            result = false;
        } else if (!isAlphabet(lastNametxt.getText())) {
            lbl1.setText("Invalid Lastname!");
            lbl1.setVisible(true);
            result = false;
        }
        if (genderGroup.isSelected(null)) {
            lbl2.setVisible(true);
            result = false;
        }
        if (addresstxt.getText().isEmpty()) {
            lbl3.setText("*Enter address");
            lbl3.setVisible(true);
            result = false;
        } else if (!isAlphabet(addresstxt.getText())) {
            lbl3.setText("Invalid Address!");
            lbl3.setVisible(true);
            result = false;
        }

        if (phonetxt.getText().isEmpty()) {
            lbl4.setText("*Enter Phone");
            lbl4.setVisible(true);
            result = false;
        } else if (!isNumeric(phonetxt.getText())) {
            lbl4.setText("Invalid Phone!");
            lbl4.setVisible(true);
            result = false;
        }
        if (emailtxt.getText().isEmpty()) {
            lbl5.setText("*Enter Email");
            lbl5.setVisible(true);
            result = false;
        } else if (!isValidEmailAddress(emailtxt.getText())) {
            lbl5.setText("Invalid Email!");
            lbl5.setVisible(true);
            result = false;
        }
        if (jComboBox1.getSelectedIndex() == 0) {
            lbl6.setVisible(true);
            result = false;
        }

        return result;

    }

    public ArrayList getDataToSave() {
        ArrayList data = new ArrayList();
        data.add(firstNametxt.getText());
        data.add(lastNametxt.getText());
        String g;
        if (rMale.isSelected()) {
            g = "male";
        } else if (rFemale.isSelected()) {
            g = "female";
        } else {
            g = "other";
        }
        data.add(g);
        data.add(addresstxt.getText());
        data.add(phonetxt.getText());
        data.add(emailtxt.getText());
        data.add(jComboBox1.getSelectedItem().toString());
        return data;
    }

    public void clearForm() {
        firstNametxt.setText("");
        lastNametxt.setText("");
        rMale.setSelected(false);
        rFemale.setSelected(false);
        rOther.setSelected(false);
        addresstxt.setText("");
        phonetxt.setText("");
        emailtxt.setText("");
        rMale.setSelected(false);
        rFemale.setSelected(false);
        rOther.setSelected(false);
        jComboBox1.setSelectedIndex(0);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (isValidInput()) {    // TODO add your handling code here:
            DbOperation d = new DbOperation();
            d.saveCustomer(getDataToSave());
            clearForm();
            JOptionPane.showMessageDialog(this, "Customer successfully registered");

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }

    public void viewStudent() {
        try {
            DbOperation dbopt = new DbOperation();
            ResultSet rs = dbopt.viewCustomerTable();

            tbl1.setModel(buildTableModel(rs));
            // TODO add your handling code here: // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void viewAtm() {
        try {
            DbOperation dbopt = new DbOperation();
            ResultSet rs = dbopt.viewAtmTable();

            tbl2.setModel(buildTableModel(rs));
            // TODO add your handling code here: // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jTabbedPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseReleased
        dltAtmBtn.setVisible(false);
        btnDltSelectedStudent.setVisible(false);
        viewStudent();
        viewAtm();// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseReleased
    public void searchingCustomer() {
        try {
            noResultlbl.setVisible(false);
            btnDltSelectedStudent.setVisible(false);

            DbOperation dbopt = new DbOperation();
            ResultSet rs = dbopt.viewFromCustomerTable(fnSearch.getText(), lnSearch.getText());
            if (!rs.isBeforeFirst()) {
                tbl1.setVisible(false);
                noResultlbl.setText("No result for name: " + fnSearch.getText() + " " + lnSearch.getText());
                noResultlbl.setVisible(true);
            } else {

                tbl1.setVisible(true);
                tbl1.setModel(buildTableModel(rs));

            }
        } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void tbl1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseReleased
        btnDltSelectedStudent.setVisible(true);
        if (evt.getClickCount() == 2) {
            btnDltSelectedStudent.setVisible(false);
            DbOperation dopt = new DbOperation();

            ArrayList a = null;
            a = dopt.viewById(tbl1.getModel().getValueAt(tbl1.getSelectedRow(), 0).toString());

            UpdatePanel up = new UpdatePanel(a);
            up.setVisible(true);
            searchingCustomer();

        }
    }//GEN-LAST:event_tbl1MouseReleased

    private void fnSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnSearchKeyReleased
        searchingCustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_fnSearchKeyReleased

    private void lnSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnSearchKeyReleased
        searchingCustomer();        // TODO add your handling code here:
    }//GEN-LAST:event_lnSearchKeyReleased

    private void btnDltSelectedStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDltSelectedStudentActionPerformed
        try {
            DbOperation dbo = new DbOperation();
            dbo.deleteCustomer(tbl1.getModel().getValueAt(tbl1.getSelectedRow(), 0).toString());

            ResultSet rs = dbo.viewCustomerTable();
            tbl1.setModel(buildTableModel(rs));
            JOptionPane.showMessageDialog(this, "Customer successfully deleted");
            btnDltSelectedStudent.setVisible(false);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDltSelectedStudentActionPerformed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        dltAtmBtn.setVisible(false);
        DbOperation dopt = new DbOperation();
        ArrayList a = null;
        ArrayList b = null;
        b = dopt.getAddressATM();
        a = dopt.getAddressCustomer();
        ArrayList c = new ArrayList();

        for (int i = 0; i < a.size(); i++) {
            if (!b.contains(a.get(i))&!c.contains(a.get(i))) {
                c.add(a.get(i));
            }
        }
        if (c.size() <= 0) {
            JOptionPane.showMessageDialog(this, "No any address with customer and without ATM");
        } else {

            AddAtm aa = new AddAtm(c);
            aa.setVisible(true);
            viewAtm();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseReleased

    private void dltAtmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltAtmBtnActionPerformed
        try {
            DbOperation dbo = new DbOperation();
            dbo.deleteAllAtm(tbl2.getModel().getValueAt(tbl2.getSelectedRow(), 0).toString());

            ResultSet rs = dbo.viewAtmTable();
            tbl2.setModel(buildTableModel(rs));
            JOptionPane.showMessageDialog(this, "All atm in this location deleted successfully");
            dltAtmBtn.setVisible(false);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_dltAtmBtnActionPerformed

    private void tbl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseReleased
        dltAtmBtn.setVisible(true);
        if (evt.getClickCount() == 2) {
            dltAtmBtn.setVisible(false);
            ManageAtm ma=new ManageAtm(tbl2.getModel().getValueAt(tbl2.getSelectedRow(), 0).toString(),tbl2.getModel().getValueAt(tbl2.getSelectedRow(), 1).toString());
            ma.setVisible(true);
            viewAtm();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_tbl2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    ButtonGroup genderGroup = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton btnDltSelectedStudent;
    private javax.swing.JButton dltAtmBtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField firstNametxt;
    private javax.swing.JTextField fnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNametxt;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JTextField lnSearch;
    private javax.swing.JLabel noResultlbl;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private javax.swing.JRadioButton rOther;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    // End of variables declaration//GEN-END:variables
}
